create table public.comprobantes (
  id uuid not null default gen_random_uuid (),
  pedido_id uuid not null,
  cliente_id uuid not null,
  tipo_operacion character varying(4) null default '0101'::character varying,
  tipo_doc_codigo character varying(2) not null,
  serie character varying(4) not null,
  correlativo integer not null,
  serie_numero character varying not null,
  comprobante_referencia_id uuid null,
  motivo_nota text null,
  fecha_emision timestamp with time zone null default now(),
  fecha_vencimiento timestamp with time zone null,
  tipo_moneda character varying(3) null default 'PEN'::character varying,
  forma_pago character varying(50) null default 'Contado'::character varying,
  mto_oper_gravadas numeric(10, 2) null default 0,
  mto_oper_exoneradas numeric(10, 2) null default 0,
  mto_oper_inafectas numeric(10, 2) null default 0,
  mto_oper_gratuitas numeric(10, 2) null default 0,
  mto_igv numeric(10, 2) null default 0,
  mto_igv_gratuitas numeric(10, 2) null default 0,
  total_impuestos numeric(10, 2) null default 0,
  valor_venta numeric(10, 2) null default 0,
  subtotal numeric(10, 2) null default 0,
  mto_imp_venta numeric(10, 2) null default 0,
  leyendas jsonb null,
  enlace_pdf text null,
  enlace_xml text null,
  enlace_cdr text null,
  apisperu_response jsonb null,
  estado_sunat character varying null default 'borrador'::character varying,
  tipo_nota_codigo character varying(2) null,
  descuento_global_monto numeric(16, 2) null default 0,
  descuento_global_codigo text null,
  constraint comprobantes_pkey primary key (id),
  constraint comprobantes_serie_numero_key unique (serie_numero),
  constraint comprobantes_descuento_global_codigo_fkey foreign KEY (descuento_global_codigo) references cat_cargos_descuentos (codigo),
  constraint comprobantes_pedido_id_fkey foreign KEY (pedido_id) references pedidos (id),
  constraint comprobantes_tipo_doc_codigo_fkey foreign KEY (tipo_doc_codigo) references cat_tipo_documento (codigo),
  constraint comprobantes_cliente_id_fkey foreign KEY (cliente_id) references clientes (id),
  constraint comprobantes_tipo_nota_codigo_fkey foreign KEY (tipo_nota_codigo) references cat_tipo_nota_credito (codigo) on update CASCADE,
  constraint comprobantes_comprobante_referencia_id_fkey foreign KEY (comprobante_referencia_id) references comprobantes (id)
) TABLESPACE pg_default;