create table public.comprobantes_detalles (
  id uuid not null default gen_random_uuid (),
  comprobante_id uuid not null,
  producto_id uuid null,
  cod_producto character varying null,
  unidad_codigo character varying(5) null default 'NIU'::character varying,
  descripcion character varying not null,
  cantidad numeric(10, 2) not null,
  mto_valor_unitario numeric(10, 4) not null,
  mto_valor_gratuito numeric(10, 4) null default 0,
  mto_precio_unitario numeric(10, 4) not null,
  mto_valor_venta numeric(10, 2) not null,
  mto_base_igv numeric(10, 2) not null,
  porcentaje_igv numeric(5, 2) null default 18,
  igv numeric(10, 2) not null,
  tip_afe_igv_codigo character varying(2) null default '10'::character varying,
  total_impuestos numeric(10, 2) not null,
  constraint comprobantes_detalles_pkey primary key (id),
  constraint comprobantes_detalles_comprobante_id_fkey foreign KEY (comprobante_id) references comprobantes (id) on delete CASCADE,
  constraint comprobantes_detalles_producto_id_fkey foreign KEY (producto_id) references productos (id),
  constraint comprobantes_detalles_tip_afe_igv_codigo_fkey foreign KEY (tip_afe_igv_codigo) references cat_tipo_afectacion_igv (codigo),
  constraint comprobantes_detalles_unidad_codigo_fkey foreign KEY (unidad_codigo) references cat_unidades_medida (codigo)
) TABLESPACE pg_default;